apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: app
        image: 498193833993.dkr.ecr.us-east-1.amazonaws.com/simple-app:19e256e72e95be92e1a16f19e134f9afa840b0ea
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-app
spec:
  selector:
    app: simple-app
  ports:
  - port: 80
  type: LoadBalancer
